version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: ready_redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes # AOF kalıcılığını açar
    volumes:
      - redis_data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: ready_redis_ui
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

volumes:
  redis_data: