events { worker_connections 1024; }

http {
    upstream dotnet-api_cluster {
        # Servis adı docker-compose ile birebir aynı olmalı ('dotnet-api')
        server dotnet-api:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://dotnet-api_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}