server {
    listen 80;

    location / {
        default_type text/html;
        return 200 "<h1>3-Tier Network Isolation Lab</h1><p>API Testi icin <a href='/api/data'>/api/data</a> adresine gidin.</p>";
    }

    # API isteklerini backend-api konteynerına proxy'ler
    location /api/ {
        proxy_pass http://backend-api:5000/api/;
    }
}